version: '3'
services:
  develop:
    build: .
    container_name: go-microservice-develop
    ports:
      - "3050:3050"
    environment:
      GIN_MODE: debug
      PORT: 3050
    command: develop
    volumes:
      - ./microservice:/go/src/github.com/archelogos/go-microservice/microservice
